RecipeBox/Models/Ing.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RecipeBox.Models
{
    public class Ing
    {
        public int IngId { get; set; }
        public string Name { get; set; }
        public List<RecipeIng> JoinEntities { get; }
       
    }
}

RecipeBox/Controllers/IngsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace RecipeBox.Controllers
{
    public class IngsController : Controller
    {
        private readonly RecipeBoxContext _db;
        public IngsController(RecipeBoxContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Ingredients for YOU";
            List<Ing> model = _db.Ings.ToList();
            return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Title = "Add Ingredient";
            return View();
        }

        [HttpPost]
        public ActionResult Create(Ing ing)
        {
            _db.Add(ing);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Ing thisIng = _db.Ings.FirstOrDefault(ing => ing.IngId == id);
            _db.Ings.Remove(thisIng);
            _db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

RecipeBox/Views/Ings/Create.cshtml
@{
    Layout = "_Layout";
}

@model RecipeBox.Models.Ing 

<div class="text-container">
<h2> Add an Ingredient to database</h2>
</div>

<div class="text-container">
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add Ingredient">
}
<hr>

<p>@Html.ActionLink("Back to Ingredients", "Index")</p>
</div>

RecipeBox/Views/Ings/Index.cshtml
@{
    Layout = "_Layout";
}

@using RecipeBox.Models;

<div class="text-container">
<h1>Ingredients</h1>
</div>

<div class="text-container">
@if (Model.Count == 0)
{
    <h3>No ingredients have been added to the site's database, you jumbo dumbo!</h3>
}
else 
{
        @foreach (Ing ing in Model)
        {
            <h5>
            @ing.Name
            @using (Html.BeginForm("Delete", "Ings"))
            {
                @Html.Hidden("id", ing.IngId)
                <input type="submit" value="Delete" />
            }
            </h5>
        }
    
}
<hr>

<p>@Html.ActionLink("Add Ingredient", "Create")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
</div>